# Generated by Django 5.2.4 on 2026-01-05 09:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Body",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        default="default", max_length=50, verbose_name="name"
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("M0", "M0"),
                            ("M1", "M1"),
                            ("M2", "M2"),
                            ("M3", "M3"),
                        ],
                        default="M0",
                        max_length=2,
                        verbose_name="level",
                    ),
                ),
                (
                    "information",
                    models.TextField(default="default", verbose_name="information"),
                ),
                ("armor", models.FloatField(default=0.0, verbose_name="armor")),
                ("max_speed", models.FloatField(default=0.0, verbose_name="max_speed")),
                (
                    "turning_speed",
                    models.FloatField(default=0.0, verbose_name="turning_speed"),
                ),
                ("weight", models.FloatField(default=0.0, verbose_name="weight")),
                ("power", models.FloatField(default=0.0, verbose_name="power")),
                ("image", models.ImageField(blank=True, null=True, upload_to="body/")),
            ],
        ),
        migrations.CreateModel(
            name="Gun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        default="default", max_length=50, verbose_name="name"
                    ),
                ),
                ("information", models.TextField(verbose_name="information")),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("M0", "M0"),
                            ("M1", "M1"),
                            ("M2", "M2"),
                            ("M3", "M3"),
                        ],
                        default="M0",
                        max_length=2,
                        verbose_name="level",
                    ),
                ),
                (
                    "damage_minute",
                    models.FloatField(default=0.0, verbose_name="damage_minute"),
                ),
                ("damage", models.FloatField(default=0.0, verbose_name="damage")),
                ("recharge", models.FloatField(default=0.0, verbose_name="recharge")),
                ("range", models.FloatField(default=0.0, verbose_name="range")),
                ("power", models.FloatField(default=0.0, verbose_name="power")),
                ("image", models.ImageField(blank=True, null=True, upload_to="guns/")),
            ],
        ),
        migrations.CreateModel(
            name="BodyComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "body",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="protanki.body",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="GunComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "gun",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="protanki.gun",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="FavoriteBody",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "body",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="protanki.body"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favorite_bodies_rel",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "body")},
            },
        ),
        migrations.CreateModel(
            name="FavoriteGun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favorite_guns_rel",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "gun",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="protanki.gun"
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "gun")},
            },
        ),
    ]
