# Generated by Django 5.2.4 on 2025-07-14 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("protanki", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Body",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="name")),
                ("information", models.TextField(verbose_name="information")),
                ("armor", models.FloatField(verbose_name="armor")),
                ("max_speed", models.FloatField(verbose_name="max_speed")),
                ("turning_speed", models.FloatField(verbose_name="turning_speed")),
                ("weight", models.FloatField(verbose_name="weight")),
                ("power", models.FloatField(verbose_name="power")),
            ],
        ),
        migrations.AddField(
            model_name="gun",
            name="damage",
            field=models.FloatField(default="1", verbose_name="damage"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="gun",
            name="damage_minute",
            field=models.FloatField(default=1, verbose_name="damage_minute"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="gun",
            name="power",
            field=models.FloatField(default=1, verbose_name="power"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="gun",
            name="range",
            field=models.FloatField(default=1, verbose_name="range"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="gun",
            name="recharge",
            field=models.FloatField(default=1, verbose_name="recharge"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="gun",
            name="information",
            field=models.TextField(verbose_name="information"),
        ),
    ]
