# Generated by Django 5.2.4 on 2025-07-23 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("protanki", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="body",
            name="level",
            field=models.CharField(
                choices=[("M0", "M0"), ("M1", "M1"), ("M2", "M2"), ("M3", "M3")],
                default="M0",
                max_length=2,
                verbose_name="level",
            ),
        ),
        migrations.AddField(
            model_name="gun",
            name="level",
            field=models.CharField(
                choices=[("M0", "M0"), ("M1", "M1"), ("M2", "M2"), ("M3", "M3")],
                default="M0",
                max_length=2,
                verbose_name="level",
            ),
        ),
        migrations.AlterField(
            model_name="body",
            name="armor",
            field=models.FloatField(default=0.0, verbose_name="armor"),
        ),
        migrations.AlterField(
            model_name="body",
            name="information",
            field=models.TextField(default=0.0, verbose_name="information"),
        ),
        migrations.AlterField(
            model_name="body",
            name="max_speed",
            field=models.FloatField(default=0.0, verbose_name="max_speed"),
        ),
        migrations.AlterField(
            model_name="body",
            name="power",
            field=models.FloatField(default=0.0, verbose_name="power"),
        ),
        migrations.AlterField(
            model_name="body",
            name="turning_speed",
            field=models.FloatField(default=0.0, verbose_name="turning_speed"),
        ),
        migrations.AlterField(
            model_name="body",
            name="weight",
            field=models.FloatField(default=0.0, verbose_name="weight"),
        ),
    ]
