# Generated by Django 5.2.4 on 2025-07-14 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("protanki", "0002_body_gun_damage_gun_damage_minute_gun_power_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="body",
            name="name",
            field=models.CharField(
                default="default", max_length=50, verbose_name="name"
            ),
        ),
        migrations.AlterField(
            model_name="gun",
            name="name",
            field=models.CharField(
                default="default", max_length=50, verbose_name="name"
            ),
        ),
    ]
