# Generated by Django 5.2.4 on 2026-01-05 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("protanki", "0002_alter_body_armor_alter_body_max_speed_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="body",
            name="armor",
            field=models.FloatField(default=0.0, verbose_name="armor"),
        ),
        migrations.AlterField(
            model_name="body",
            name="max_speed",
            field=models.FloatField(default=0.0, verbose_name="max_speed"),
        ),
        migrations.AlterField(
            model_name="body",
            name="power",
            field=models.FloatField(default=0.0, verbose_name="power"),
        ),
        migrations.AlterField(
            model_name="body",
            name="turning_speed",
            field=models.FloatField(default=0.0, verbose_name="turning_speed"),
        ),
        migrations.AlterField(
            model_name="body",
            name="weight",
            field=models.FloatField(default=0.0, verbose_name="weight"),
        ),
        migrations.AlterField(
            model_name="gun",
            name="damage",
            field=models.FloatField(default=0.0, verbose_name="damage"),
        ),
        migrations.AlterField(
            model_name="gun",
            name="damage_minute",
            field=models.FloatField(default=0.0, verbose_name="damage_minute"),
        ),
        migrations.AlterField(
            model_name="gun",
            name="power",
            field=models.FloatField(default=0.0, verbose_name="power"),
        ),
        migrations.AlterField(
            model_name="gun",
            name="range",
            field=models.FloatField(default=0.0, verbose_name="range"),
        ),
        migrations.AlterField(
            model_name="gun",
            name="recharge",
            field=models.FloatField(default=0.0, verbose_name="recharge"),
        ),
    ]
