# Generated by Django 5.2.4 on 2025-07-24 09:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("protanki", "0003_favoritebody_favoritegun"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="favoritebody",
            name="body",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="protanki.body"
            ),
        ),
        migrations.AlterField(
            model_name="favoritebody",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="favorite_bodies_rel",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="favoritegun",
            name="gun",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="protanki.gun"
            ),
        ),
        migrations.AlterField(
            model_name="favoritegun",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="favorite_guns_rel",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
