# Generated by Django 5.2.4 on 2025-07-14 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("protanki", "0003_alter_body_name_alter_gun_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gun",
            name="damage_minute",
            field=models.FloatField(default=0, verbose_name="damage_minute"),
        ),
    ]
