# Generated by Django 5.2.4 on 2025-08-12 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("protanki", "0004_alter_favoritebody_body_alter_favoritebody_user_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="body",
            name="information",
            field=models.TextField(default="default", verbose_name="information"),
        ),
    ]
