# Generated by Django 5.2.4 on 2025-07-14 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("protanki", "0005_alter_gun_damage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gun",
            name="power",
            field=models.FloatField(default=0, verbose_name="power"),
        ),
        migrations.AlterField(
            model_name="gun",
            name="range",
            field=models.FloatField(default=0, verbose_name="range"),
        ),
        migrations.AlterField(
            model_name="gun",
            name="recharge",
            field=models.FloatField(default=0, verbose_name="recharge"),
        ),
    ]
