# Generated by Django 5.2.4 on 2025-08-21 14:05

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("protanki", "0005_alter_body_information"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name="favoritegun",
            old_name="gun",
            new_name="gun_id",
        ),
        migrations.AlterUniqueTogether(
            name="favoritegun",
            unique_together={("user", "gun_id")},
        ),
    ]
