# Generated by Django 5.2.4 on 2025-07-14 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("protanki", "0006_alter_gun_power_alter_gun_range_alter_gun_recharge"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="gun",
            name="damage_minute",
        ),
    ]
