# Generated by Django 5.2.4 on 2025-07-14 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("protanki", "0007_remove_gun_damage_minute"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="gun",
            name="damage",
        ),
    ]
