# Generated by Django 5.2.4 on 2025-07-14 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("protanki", "0008_remove_gun_damage"),
    ]

    operations = [
        migrations.AddField(
            model_name="gun",
            name="damage",
            field=models.FloatField(default=0.0, verbose_name="damage"),
        ),
        migrations.AddField(
            model_name="gun",
            name="damage_minute",
            field=models.FloatField(default=0.0, verbose_name="damage_minute"),
        ),
    ]
