# Generated by Django 5.2.4 on 2025-07-14 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("protanki", "0009_gun_damage_gun_damage_minute"),
    ]

    operations = [
        migrations.AddField(
            model_name="gun",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="guns/"),
        ),
    ]
